FROM golang:1.9.0-alpine as build

WORKDIR /go/src/github.com/lucj/who

COPY http.go .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o http .

FROM scratch

COPY --from=build /go/src/github.com/lucj/who/http .

CMD ["./http"]
